In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd


url = "https://www.globalfirepower.com/aircraft-total-fighters.php"
response = requests.get(url)
soup = BeautifulSoup(response.text, "lxml")

countries = soup.find_all("a", href=True)

data = []

for country in countries:
    # Rank
    rank_tag = country.select_one(".rankNumContainer span")
    rank = rank_tag.text.strip() if rank_tag else None

    # Full Country Name
    full_name_tag = country.select_one(".longFormName span")
    full_name = full_name_tag.text.strip() if full_name_tag else None

    # Short Country Name
    short_name_tag = country.select_one(".shortFormName span")
    short_name = short_name_tag.text.strip() if short_name_tag else None

    # Value
    value_tag = country.select_one(".valueContainer span span")
    value = value_tag.text.strip() if value_tag else None

    # Store only valid country rows
    if rank and full_name and value:
        data.append({
            "Rank": rank,
            "Country_Full_Name": full_name,
            "Country_Short_Name": short_name,
            "Value": value
        })


print(url,"Scraping is Completd.")

https://www.globalfirepower.com/aircraft-total-fighters.php Scraping is Completd.

In [4]:
# Print results
for d in data[:5]:   # show first 5
    print(d)

{'Rank': '1', 'Country_Full_Name': 'United States', 'Country_Short_Name': 'USA', 'Value': '1,790'}
{'Rank': '2', 'Country_Full_Name': 'China', 'Country_Short_Name': 'CHN', 'Value': '1,212'}
{'Rank': '3', 'Country_Full_Name': 'Russia', 'Country_Short_Name': 'RUS', 'Value': '833'}
{'Rank': '4', 'Country_Full_Name': 'India', 'Country_Short_Name': 'IND', 'Value': '513'}
{'Rank': '5', 'Country_Full_Name': 'North Korea', 'Country_Short_Name': 'NKO', 'Value': '368'}

In [6]:
df = pd.DataFrame(data)
df

    Rank Country_Full_Name Country_Short_Name  Value
0      1     United States                USA  1,790
1      2             China                CHN  1,212
2      3            Russia                RUS    833
3      4             India                IND    513
4      5       North Korea                NKO    368
..   ...               ...                ...    ...
140  141       South Sudan                SSD      0
141  142          Suriname                SRN      0
142  143        Tajikistan                TJK      0
143  144           Uruguay                URU      0
144  145            Zambia                ZAM      0

[145 rows x 4 columns]

In [7]:
df.head()

  Rank Country_Full_Name Country_Short_Name  Value
0    1     United States                USA  1,790
1    2             China                CHN  1,212
2    3            Russia                RUS    833
3    4             India                IND    513
4    5       North Korea                NKO    368

In [8]:
df.tail()

    Rank Country_Full_Name Country_Short_Name Value
140  141       South Sudan                SSD     0
141  142          Suriname                SRN     0
142  143        Tajikistan                TJK     0
143  144           Uruguay                URU     0
144  145            Zambia                ZAM     0

In [9]:
df.to_csv("aircraft-total-fighters_scrape_military_metrics.csv", index=False)
print("CSV file saved successfully ")

CSV file saved successfully

In [10]:
urls = [
    "https://www.globalfirepower.com/total-population-by-country.php",
    "https://www.globalfirepower.com/available-military-manpower.php",
    "https://www.globalfirepower.com/manpower-fit-for-military-service.php",
    "https://www.globalfirepower.com/manpower-reaching-military-age-annually.php",
    "https://www.globalfirepower.com/active-military-manpower.php",
    "https://www.globalfirepower.com/active-reserve-military-manpower.php",
    "https://www.globalfirepower.com/manpower-paramilitary.php",

    "https://www.globalfirepower.com/aircraft-total.php",
    "https://www.globalfirepower.com/aircraft-total-fighters.php",
    "https://www.globalfirepower.com/aircraft-total-attack-types.php",
    "https://www.globalfirepower.com/aircraft-total-transports.php",
    "https://www.globalfirepower.com/aircraft-total-trainers.php",
    "https://www.globalfirepower.com/aircraft-total-special-mission.php",
    "https://www.globalfirepower.com/aircraft-total-tanker-fleet.php",
    "https://www.globalfirepower.com/aircraft-helicopters-total.php",
    "https://www.globalfirepower.com/aircraft-helicopters-attack.php",

    "https://www.globalfirepower.com/armor-tanks-total.php",
    "https://www.globalfirepower.com/armor-apc-total.php",
    "https://www.globalfirepower.com/armor-self-propelled-guns-total.php",
    "https://www.globalfirepower.com/armor-towed-artillery-total.php",
    "https://www.globalfirepower.com/armor-mlrs-total.php",

    "https://www.globalfirepower.com/navy-ships.php",
    "https://www.globalfirepower.com/navy-force-by-tonnage.php",
    "https://www.globalfirepower.com/navy-aircraft-carriers.php",
    "https://www.globalfirepower.com/navy-helo-carriers.php",
    "https://www.globalfirepower.com/navy-submarines.php",
    "https://www.globalfirepower.com/navy-destroyers.php",
    "https://www.globalfirepower.com/navy-frigates.php",
    "https://www.globalfirepower.com/navy-corvettes.php",
    "https://www.globalfirepower.com/navy-patrol-coastal-craft.php",
    "https://www.globalfirepower.com/navy-mine-warfare-craft.php",

    "https://www.globalfirepower.com/defense-spending-budget.php",
    "https://www.globalfirepower.com/external-debt-by-country.php",
    "https://www.globalfirepower.com/purchasing-power-parity.php",
    "https://www.globalfirepower.com/reserves-of-foreign-exchange-and-gold.php",

    "https://www.globalfirepower.com/major-serviceable-airports-by-country.php",
    "https://www.globalfirepower.com/labor-force-by-country.php",
    "https://www.globalfirepower.com/major-ports-and-terminals.php",
    "https://www.globalfirepower.com/merchant-marine-strength-by-country.php",

    "https://www.globalfirepower.com/railway-coverage.php",
    "https://www.globalfirepower.com/roadway-coverage.php",

    "https://www.globalfirepower.com/oil-production-by-country.php",
    "https://www.globalfirepower.com/oil-consumption-by-country.php",
    "https://www.globalfirepower.com/proven-oil-reserves-by-country.php",
    "https://www.globalfirepower.com/natural-gas-production-by-country.php",
    "https://www.globalfirepower.com/natural-gas-consumption-by-country.php",
    "https://www.globalfirepower.com/proven-natural-gas-reserves-by-country.php",
    "https://www.globalfirepower.com/coal-production-by-country.php",
    "https://www.globalfirepower.com/coal-consumption-by-country.php",
    "https://www.globalfirepower.com/proven-coal-reserves-by-country.php",

    "https://www.globalfirepower.com/square-land-area.php",
    "https://www.globalfirepower.com/coastline-coverage.php",
    "https://www.globalfirepower.com/border-coverage.php",
    "https://www.globalfirepower.com/waterway-coverage.php"
]

In [20]:
import pandas as pd

urls_data = pd.DataFrame(urls, columns=["all_url"])
urls_data.index = range(1, len(urls_data) + 1)

print(f"Total URLs count: {len(urls_data)}")
urls_data.head()

Total URLs count: 54

                                             all_url
1  https://www.globalfirepower.com/total-populati...
2  https://www.globalfirepower.com/available-mili...
3  https://www.globalfirepower.com/manpower-fit-f...
4  https://www.globalfirepower.com/manpower-reach...
5  https://www.globalfirepower.com/active-militar...

In [21]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

HEADERS = {
    "User-Agent": "Mozilla/5.0"
}


all_data = []


def extract_category_and_metric(soup, url):
    h1 = soup.find("h1")
    metric = h1.text.strip() if h1 else url.split("/")[-1].replace(".php", "")

    if "aircraft" in url:
        category = "Air Force"
    elif "armor" in url:
        category = "Army (Armor)"
    elif "navy" in url:
        category = "Navy"
    elif "manpower" in url or "population" in url:
        category = "Manpower"
    elif "budget" in url or "debt" in url:
        category = "Defense & Economy"
    elif "oil" in url or "gas" in url or "coal" in url:
        category = "Energy & Resources"
    elif "land" in url or "coastline" in url:
        category = "Geography"
    else:
        category = "Other"

    return category, metric


def scrape_page(url):
    print(f"Scraping → {url}")
    r = requests.get(url, headers=HEADERS)
    soup = BeautifulSoup(r.text, "lxml")

    category, metric = extract_category_and_metric(soup, url)

    for card in soup.select("a[href*='country-military-strength-detail']"):
        rank = card.select_one(".rankNumContainer span")
        full = card.select_one(".longFormName span")
        short = card.select_one(".shortFormName span")
        value = card.select_one(".valueContainer span span")

        if rank and full and value:
            all_data.append({
                "Category": category,
                "Category_URL": url,
                "Metric": metric,
                "Rank": rank.text.strip(),
                "Country_Full_Name": full.text.strip(),
                "Country_Short_Name": short.text.strip() if short else None,
                "Value": value.text.strip()
            })

In [22]:
for url in urls:
    scrape_page(url)
    time.sleep(2)

Scraping → https://www.globalfirepower.com/total-population-by-country.php
Scraping → https://www.globalfirepower.com/available-military-manpower.php
Scraping → https://www.globalfirepower.com/manpower-fit-for-military-service.php
Scraping → https://www.globalfirepower.com/manpower-reaching-military-age-annually.php
Scraping → https://www.globalfirepower.com/active-military-manpower.php
Scraping → https://www.globalfirepower.com/active-reserve-military-manpower.php
Scraping → https://www.globalfirepower.com/manpower-paramilitary.php
Scraping → https://www.globalfirepower.com/aircraft-total.php
Scraping → https://www.globalfirepower.com/aircraft-total-fighters.php
Scraping → https://www.globalfirepower.com/aircraft-total-attack-types.php
Scraping → https://www.globalfirepower.com/aircraft-total-transports.php
Scraping → https://www.globalfirepower.com/aircraft-total-trainers.php
Scraping → https://www.globalfirepower.com/aircraft-total-special-mission.php
Scraping → https://www.globalfirepower.com/aircraft-total-tanker-fleet.php
Scraping → https://www.globalfirepower.com/aircraft-helicopters-total.php
Scraping → https://www.globalfirepower.com/aircraft-helicopters-attack.php
Scraping → https://www.globalfirepower.com/armor-tanks-total.php
Scraping → https://www.globalfirepower.com/armor-apc-total.php
Scraping → https://www.globalfirepower.com/armor-self-propelled-guns-total.php
Scraping → https://www.globalfirepower.com/armor-towed-artillery-total.php
Scraping → https://www.globalfirepower.com/armor-mlrs-total.php
Scraping → https://www.globalfirepower.com/navy-ships.php
Scraping → https://www.globalfirepower.com/navy-force-by-tonnage.php
Scraping → https://www.globalfirepower.com/navy-aircraft-carriers.php
Scraping → https://www.globalfirepower.com/navy-helo-carriers.php
Scraping → https://www.globalfirepower.com/navy-submarines.php
Scraping → https://www.globalfirepower.com/navy-destroyers.php
Scraping → https://www.globalfirepower.com/navy-frigates.php
Scraping → https://www.globalfirepower.com/navy-corvettes.php
Scraping → https://www.globalfirepower.com/navy-patrol-coastal-craft.php
Scraping → https://www.globalfirepower.com/navy-mine-warfare-craft.php
Scraping → https://www.globalfirepower.com/defense-spending-budget.php
Scraping → https://www.globalfirepower.com/external-debt-by-country.php
Scraping → https://www.globalfirepower.com/purchasing-power-parity.php
Scraping → https://www.globalfirepower.com/reserves-of-foreign-exchange-and-gold.php
Scraping → https://www.globalfirepower.com/major-serviceable-airports-by-country.php
Scraping → https://www.globalfirepower.com/labor-force-by-country.php
Scraping → https://www.globalfirepower.com/major-ports-and-terminals.php
Scraping → https://www.globalfirepower.com/merchant-marine-strength-by-country.php
Scraping → https://www.globalfirepower.com/railway-coverage.php
Scraping → https://www.globalfirepower.com/roadway-coverage.php
Scraping → https://www.globalfirepower.com/oil-production-by-country.php
Scraping → https://www.globalfirepower.com/oil-consumption-by-country.php
Scraping → https://www.globalfirepower.com/proven-oil-reserves-by-country.php
Scraping → https://www.globalfirepower.com/natural-gas-production-by-country.php
Scraping → https://www.globalfirepower.com/natural-gas-consumption-by-country.php
Scraping → https://www.globalfirepower.com/proven-natural-gas-reserves-by-country.php
Scraping → https://www.globalfirepower.com/coal-production-by-country.php
Scraping → https://www.globalfirepower.com/coal-consumption-by-country.php
Scraping → https://www.globalfirepower.com/proven-coal-reserves-by-country.php
Scraping → https://www.globalfirepower.com/square-land-area.php
Scraping → https://www.globalfirepower.com/coastline-coverage.php
Scraping → https://www.globalfirepower.com/border-coverage.php
Scraping → https://www.globalfirepower.com/waterway-coverage.php

In [23]:
df = pd.DataFrame(all_data)
df.to_csv("military_raw_data.csv", index=False)

print("Data scraped and saved successfully")

Data scraped and saved successfully

In [24]:
print("Total rows:", df.shape[0])

Total rows: 7732

In [25]:
df.head()

,Category,Category_URL,Metric,Rank,Country_Full_Name,Country_Short_Name,Value
0,Manpower,https://www.globalfirepower.com/total-populati...,Total Population by Country (2025),1,China,CHN,"1,415,043,270"
1,Manpower,https://www.globalfirepower.com/total-populati...,Total Population by Country (2025),2,India,IND,"1,409,128,296"
2,Manpower,https://www.globalfirepower.com/total-populati...,Total Population by Country (2025),3,United States,USA,"341,963,408"
3,Manpower,https://www.globalfirepower.com/total-populati...,Total Population by Country (2025),4,Indonesia,INO,"281,562,465"
4,Manpower,https://www.globalfirepower.com/total-populati...,Total Population by Country (2025),5,Pakistan,PAK,"252,363,571"

In [52]:
unique_urls = df.Category_URL.unique()

print(f"\nTotal count of URLs successfully scraped: {len(unique_urls)}")
print("Unique Category URLs:")
cnt = 1
for url in unique_urls:
    print(f'{cnt} {url}')
    cnt += 1

Total count of URLs successfully scraped: 54
Unique Category URLs:
1 https://www.globalfirepower.com/total-population-by-country.php
2 https://www.globalfirepower.com/available-military-manpower.php
3 https://www.globalfirepower.com/manpower-fit-for-military-service.php
4 https://www.globalfirepower.com/manpower-reaching-military-age-annually.php
5 https://www.globalfirepower.com/active-military-manpower.php
6 https://www.globalfirepower.com/active-reserve-military-manpower.php
7 https://www.globalfirepower.com/manpower-paramilitary.php
8 https://www.globalfirepower.com/aircraft-total.php
9 https://www.globalfirepower.com/aircraft-total-fighters.php
10 https://www.globalfirepower.com/aircraft-total-attack-types.php
11 https://www.globalfirepower.com/aircraft-total-transports.php
12 https://www.globalfirepower.com/aircraft-total-trainers.php
13 https://www.globalfirepower.com/aircraft-total-special-mission.php
14 https://www.globalfirepower.com/aircraft-total-tanker-fleet.php
15 https://www.globalfirepower.com/aircraft-helicopters-total.php
16 https://www.globalfirepower.com/aircraft-helicopters-attack.php
17 https://www.globalfirepower.com/armor-tanks-total.php
18 https://www.globalfirepower.com/armor-apc-total.php
19 https://www.globalfirepower.com/armor-self-propelled-guns-total.php
20 https://www.globalfirepower.com/armor-towed-artillery-total.php
21 https://www.globalfirepower.com/armor-mlrs-total.php
22 https://www.globalfirepower.com/navy-ships.php
23 https://www.globalfirepower.com/navy-force-by-tonnage.php
24 https://www.globalfirepower.com/navy-aircraft-carriers.php
25 https://www.globalfirepower.com/navy-helo-carriers.php
26 https://www.globalfirepower.com/navy-submarines.php
27 https://www.globalfirepower.com/navy-destroyers.php
28 https://www.globalfirepower.com/navy-frigates.php
29 https://www.globalfirepower.com/navy-corvettes.php
30 https://www.globalfirepower.com/navy-patrol-coastal-craft.php
31 https://www.globalfirepower.com/navy-mine-warfare-craft.php
32 https://www.globalfirepower.com/defense-spending-budget.php
33 https://www.globalfirepower.com/external-debt-by-country.php
34 https://www.globalfirepower.com/purchasing-power-parity.php
35 https://www.globalfirepower.com/reserves-of-foreign-exchange-and-gold.php
36 https://www.globalfirepower.com/major-serviceable-airports-by-country.php
37 https://www.globalfirepower.com/labor-force-by-country.php
38 https://www.globalfirepower.com/major-ports-and-terminals.php
39 https://www.globalfirepower.com/merchant-marine-strength-by-country.php
40 https://www.globalfirepower.com/railway-coverage.php
41 https://www.globalfirepower.com/roadway-coverage.php
42 https://www.globalfirepower.com/oil-production-by-country.php
43 https://www.globalfirepower.com/oil-consumption-by-country.php
44 https://www.globalfirepower.com/proven-oil-reserves-by-country.php
45 https://www.globalfirepower.com/natural-gas-production-by-country.php
46 https://www.globalfirepower.com/natural-gas-consumption-by-country.php
47 https://www.globalfirepower.com/proven-natural-gas-reserves-by-country.php
48 https://www.globalfirepower.com/coal-production-by-country.php
49 https://www.globalfirepower.com/coal-consumption-by-country.php
50 https://www.globalfirepower.com/proven-coal-reserves-by-country.php
51 https://www.globalfirepower.com/square-land-area.php
52 https://www.globalfirepower.com/coastline-coverage.php
53 https://www.globalfirepower.com/border-coverage.php
54 https://www.globalfirepower.com/waterway-coverage.php

In [53]:
unique_country_names = df.Country_Full_Name.unique()

print(f"\nTotal count of unique Country Full Names: {len(unique_country_names)}")
print("Unique Country Full Names:")
cnt = 1
for name in unique_country_names:
    print(f'{cnt} {name}')
    cnt += 1

Total count of unique Country Full Names: 145
Unique Country Full Names:
1 China
2 India
3 United States
4 Indonesia
5 Pakistan
6 Nigeria
7 Brazil
8 Bangladesh
9 Russia
10 Mexico
11 Japan
12 Ethiopia
13 Philippines
14 Democratic Republic of the Congo
15 Egypt
16 Vietnam
17 Iran
18 Turkiye
19 Germany
20 Thailand
21 United Kingdom
22 France
23 Tanzania
24 Italy
25 South Africa
26 Kenya
27 Myanmar
28 South Korea
29 Sudan
30 Colombia
31 Uganda
32 Spain
33 Algeria
34 Argentina
35 Iraq
36 Afghanistan
37 Canada
38 Poland
39 Morocco
40 Angola
41 Saudi Arabia
42 Uzbekistan
43 Ukraine
44 Ghana
45 Malaysia
46 Mozambique
47 Peru
48 Yemen
49 Venezuela
50 Nepal
51 Cameroon
52 Ivory Coast
53 Madagascar
54 Australia
55 Niger
56 North Korea
57 Syria
58 Taiwan
59 Burkina Faso
60 Mali
61 Sri Lanka
62 Zambia
63 Kazakhstan
64 Chad
65 Senegal
66 Chile
67 Ecuador
68 Guatemala
69 Romania
70 Netherlands
71 Zimbabwe
72 Cambodia
73 Benin
74 Somalia
75 South Sudan
76 Bolivia
77 Tunisia
78 Belgium
79 Jordan
80 Cuba
81 Czechia
82 Dominican Republic
83 Azerbaijan
84 Portugal
85 Sweden
86 Greece
87 Tajikistan
88 United Arab Emirates
89 Hungary
90 Honduras
91 Belarus
92 Israel
93 Sierra Leone
94 Austria
95 Switzerland
96 Laos
97 Paraguay
98 Libya
99 Bulgaria
100 Nicaragua
101 Serbia
102 El Salvador
103 Eritrea
104 Kyrgyzstan
105 Republic of the Congo
106 Singapore
107 Denmark
108 Turkmenistan
109 Central African Republic
110 Finland
111 Slovakia
112 Norway
113 Liberia
114 Lebanon
115 Ireland
116 New Zealand
117 Georgia
118 Panama
119 Mauritania
120 Croatia
121 Oman
122 Bosnia and Herzegovina
123 Moldova
124 Uruguay
125 Mongolia
126 Kuwait
127 Albania
128 Armenia
129 Namibia
130 Lithuania
131 Qatar
132 Gabon
133 Botswana
134 North Macedonia
135 Slovenia
136 Kosovo
137 Latvia
138 Bahrain
139 Estonia
140 Bhutan
141 Luxembourg
142 Suriname
143 Montenegro
144 Beliz
145 Iceland

#**To save the military_raw_data.csv file to Drive**

In [27]:
# df.to_csv("/content/drive/MyDrive/Colab Notebooks/module 1/military_raw_data.csv", index=False)
# print("CSV file saved successfully ")

CSV file saved successfully