In [ ]:
import pandas as pd
df = pd.read_csv(r"/content/Output_for_Milestone1.csv")
print("Columns count:", len(df.columns))

columns_to_drop = [
    "oil_consumption_bbl",
    "oil_production_bbl",
    "natural_gas_consumption_cum",
    "natural_gas_production_cum",
    "coal_consumption_mt",
    "coal_production_cum",
    "proven_oil_reserves_bbl",
    "proven_natural_gas_reserves_cum",
    "proven_coal_reserves_cum",
    "labour_force",
    "external_debt_usd",
    "foreign_exchange_and_gold_reserves_usd",
    "total_merchant_marine_fleet",
    "mine_warfare_craft"
]

df.drop(columns=[col for col in columns_to_drop if col in df.columns],inplace=True)

print("Unnecessary columns removed successfully.")
print("Final columns count:", len(df.columns))

Columns count: 54
Unnecessary columns removed successfully.
Final columns count: 40

In [ ]:
df.head()

,country,active_personnel,aircraft_carriers,armored_fighting_vehicles,attack_aircraft,attack_helicopters,border_coverage_km,coastal_patrol_craft,coastline_coverage_km,corvettes,...,total_military_aircraft,total_military_helicopters,total_military_manpower,total_naval_fleet,total_population,total_serviceable_airports,towed_artillery,trainer_aircraft,transport_aircraft,waterway_coverage_km
0,Afghanistan,0,0,5202,0,1,5987,0,0,0,...,9,6,15647405,0,40121552,67,0,0,3,1200
1,Albania,6600,0,1796,0,0,691,19,362,0,...,19,19,1522479,19,3107100,3,50,0,0,41
2,Algeria,325000,0,26000,42,74,6734,75,998,8,...,608,299,22570787,110,47022473,85,483,87,63,0
3,Angola,107000,0,5500,12,15,5369,29,1600,0,...,298,116,7440412,31,37202061,106,575,66,31,1300
4,Argentina,108000,0,21724,11,0,11968,13,4989,6,...,239,94,20677529,44,46994384,756,172,71,52,11000

In [ ]:
#Power Index Rank Gap
df['Power_Score']=df['active_personnel']+df['tanks']+df['total_military_aircraft']+df['total_naval_fleet']
df["Power_Rank"] = df["Power_Score"].rank(ascending=False, method="min")
df["Power_Index_Rank_Gap"] = df["Power_Rank"] - 1

In [ ]:
df.columns

Index(['country', 'active_personnel', 'aircraft_carriers',
       'armored_fighting_vehicles', 'attack_aircraft', 'attack_helicopters',
       'border_coverage_km', 'coastal_patrol_craft', 'coastline_coverage_km',
       'corvettes', 'defense_budget_usd', 'destroyers', 'fighter_aircraft',
       'fit_for_service', 'frigates', 'helicopter_carriers',
       'major_ports_and_terminals', 'paramilitary',
       'population_reaching_military_age_annually',
       'purchasing_power_parity_usd', 'railway_coverage_km',
       'reserve_personnel', 'roadway_coverage_km', 'rocket_projectors',
       'self_propelled_artillery', 'special_mission_aircraft', 'submarines',
       'tanker_aircraft', 'tanks', 'total_land_area_sq_km',
       'total_military_aircraft', 'total_military_helicopters',
       'total_military_manpower', 'total_naval_fleet', 'total_population',
       'total_serviceable_airports', 'towed_artillery', 'trainer_aircraft',
       'transport_aircraft', 'waterway_coverage_km', 'Power_Score',
       'Power_Rank', 'Power_Index_Rank_Gap'],
      dtype='object')

In [ ]:
#Assets per Capita
df["Total_Assets"] = (df["tanks"]+df["total_military_aircraft"]+df["total_naval_fleet"])
df["Assets_Per_Capita"] = df["Total_Assets"]/df["total_population"]

In [ ]:
#Budget-to-GDP Ratio
df["Budget_to_GDP_Ratio"] = (df["defense_budget_usd"] / df["purchasing_power_parity_usd"])

In [ ]:
df['country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahrain',
       'Bangladesh', 'Belarus', 'Belgium', 'Beliz', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Cambodia', 'Cameroon', 'Canada',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Croatia', 'Cuba', 'Czechia', 'Democratic Republic of the Congo',
       'Denmark', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
       'Eritrea', 'Estonia', 'Ethiopia', 'Finland', 'France', 'Gabon',
       'Georgia', 'Germany', 'Ghana', 'Greece', 'Guatemala', 'Honduras',
       'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq',
       'Ireland', 'Israel', 'Italy', 'Ivory Coast', 'Japan', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos',
       'Latvia', 'Lebanon', 'Liberia', 'Libya', 'Lithuania', 'Luxembourg',
       'Madagascar', 'Malaysia', 'Mali', 'Mauritania', 'Mexico',
       'Moldova', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique',
       'Myanmar', 'Namibia', 'Nepal', 'Netherlands', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'North Macedonia',
       'Norway', 'Oman', 'Pakistan', 'Panama', 'Paraguay', 'Peru',
       'Philippines', 'Poland', 'Portugal', 'Qatar',
       'Republic of the Congo', 'Romania', 'Russia', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Sierra Leone', 'Singapore', 'Slovakia',
       'Slovenia', 'Somalia', 'South Africa', 'South Korea',
       'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden',
       'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania',
       'Thailand', 'Tunisia', 'Turkiye', 'Turkmenistan', 'Uganda',
       'Ukraine', 'United Arab Emirates', 'United Kingdom',
       'United States', 'Uruguay', 'Uzbekistan', 'Venezuela', 'Vietnam',
       'Yemen', 'Zambia', 'Zimbabwe'], dtype=object)

In [ ]:
# NATO member countries (2025 approx.)
nato_countries = {
    "United States", "United Kingdom", "France", "Germany", "Italy",
    "Spain", "Portugal", "Belgium", "Netherlands", "Luxembourg",
    "Canada", "Denmark", "Norway", "Iceland", "Poland", "Czechia",
    "Slovakia", "Hungary", "Romania", "Bulgaria", "Croatia",
    "Slovenia", "Estonia", "Latvia", "Lithuania", "Finland",
    "Sweden", "Montenegro", "North Macedonia", "Albania", "Türkiye"
}

In [ ]:
continent_map = {
    # Asia
    "Afghanistan": "Asia", "Bangladesh": "Asia", "Bhutan": "Asia",
    "Cambodia": "Asia", "China": "Asia", "India": "Asia", "Indonesia": "Asia",
    "Iran": "Asia", "Iraq": "Asia", "Israel": "Asia", "Japan": "Asia",
    "Jordan": "Asia", "Kazakhstan": "Asia", "Kuwait": "Asia",
    "Kyrgyzstan": "Asia", "Laos": "Asia", "Lebanon": "Asia", "Malaysia": "Asia",
    "Mongolia": "Asia", "Myanmar": "Asia", "Nepal": "Asia",
    "North Korea": "Asia", "Oman": "Asia", "Pakistan": "Asia",
    "Philippines": "Asia", "Qatar": "Asia", "Saudi Arabia": "Asia",
    "Singapore": "Asia", "South Korea": "Asia", "Sri Lanka": "Asia",
    "Syria": "Asia", "Taiwan": "Asia", "Tajikistan": "Asia",
    "Thailand": "Asia", "Turkmenistan": "Asia", "United Arab Emirates": "Asia",
    "Uzbekistan": "Asia", "Vietnam": "Asia", "Yemen": "Asia",

    # Europe
    "Albania": "Europe", "Austria": "Europe", "Belarus": "Europe",
    "Belgium": "Europe", "Bosnia and Herzegovina": "Europe",
    "Bulgaria": "Europe", "Croatia": "Europe", "Czechia": "Europe",
    "Denmark": "Europe", "Estonia": "Europe", "Finland": "Europe",
    "France": "Europe", "Georgia": "Europe", "Germany": "Europe",
    "Greece": "Europe", "Hungary": "Europe", "Iceland": "Europe",
    "Ireland": "Europe", "Italy": "Europe", "Kosovo": "Europe",
    "Latvia": "Europe", "Lithuania": "Europe", "Luxembourg": "Europe",
    "Moldova": "Europe", "Montenegro": "Europe", "Netherlands": "Europe",
    "North Macedonia": "Europe", "Norway": "Europe", "Poland": "Europe",
    "Portugal": "Europe", "Romania": "Europe", "Russia": "Europe",
    "Serbia": "Europe", "Slovakia": "Europe", "Slovenia": "Europe",
    "Spain": "Europe", "Sweden": "Europe", "Switzerland": "Europe",
    "Ukraine": "Europe", "United Kingdom": "Europe",

    # Africa
    "Algeria": "Africa", "Angola": "Africa", "Benin": "Africa",
    "Botswana": "Africa", "Burkina Faso": "Africa", "Cameroon": "Africa",
    "Central African Republic": "Africa", "Chad": "Africa",
    "Democratic Republic of the Congo": "Africa", "Republic of the Congo": "Africa",
    "Egypt": "Africa", "Eritrea": "Africa", "Ethiopia": "Africa",
    "Gabon": "Africa", "Ghana": "Africa", "Ivory Coast": "Africa",
    "Kenya": "Africa", "Liberia": "Africa", "Libya": "Africa",
    "Madagascar": "Africa", "Mali": "Africa", "Mauritania": "Africa",
    "Morocco": "Africa", "Mozambique": "Africa", "Namibia": "Africa",
    "Niger": "Africa", "Nigeria": "Africa", "Senegal": "Africa",
    "Sierra Leone": "Africa", "Somalia": "Africa", "South Africa": "Africa",
    "South Sudan": "Africa", "Sudan": "Africa", "Tanzania": "Africa",
    "Tunisia": "Africa", "Uganda": "Africa", "Zambia": "Africa", "Zimbabwe": "Africa",

    # North America
    "Canada": "North America", "United States": "North America",
    "Mexico": "North America", "Guatemala": "North America",
    "Honduras": "North America", "Nicaragua": "North America",
    "Panama": "North America", "Beliz": "North America",
    "Dominican Republic": "North America", "El Salvador": "North America",
    "Cuba": "North America",

    # South America
    "Argentina": "South America", "Bolivia": "South America", "Brazil": "South America",
    "Chile": "South America", "Colombia": "South America", "Ecuador": "South America",
    "Paraguay": "South America", "Peru": "South America", "Suriname": "South America",
    "Uruguay": "South America", "Venezuela": "South America",

    # Oceania
    "Australia": "Oceania", "New Zealand": "Oceania"
}

In [ ]:
df["Continent"] = df["country"].map(continent_map).fillna("Unknown")

df["Region"] = df["Continent"]

df["Alliance"] = df["country"].apply(
    lambda x: "NATO" if x in nato_countries else "Non-NATO"
)

In [ ]:
df.head()

,country,active_personnel,aircraft_carriers,armored_fighting_vehicles,attack_aircraft,attack_helicopters,border_coverage_km,coastal_patrol_craft,coastline_coverage_km,corvettes,...,waterway_coverage_km,Power_Score,Power_Rank,Power_Index_Rank_Gap,Total_Assets,Assets_Per_Capita,Budget_to_GDP_Ratio,Continent,Region,Alliance
0,Afghanistan,0,0,5202,0,1,5987,0,0,0,...,1200,9,144.0,143.0,9,2.243183e-07,0.005295,Asia,Asia,Non-NATO
1,Albania,6600,0,1796,0,0,691,19,362,0,...,41,6684,135.0,134.0,84,2.703486e-05,0.011269,Europe,Europe,NATO
2,Algeria,325000,0,26000,42,74,6734,75,998,8,...,0,327203,18.0,17.0,2203,4.684994e-05,0.035717,Africa,Africa,Non-NATO
3,Angola,107000,0,5500,12,15,5369,29,1600,0,...,1300,107638,49.0,48.0,638,1.714959e-05,0.004143,Africa,Africa,Non-NATO
4,Argentina,108000,0,21724,11,0,11968,13,4989,6,...,11000,108625,48.0,47.0,625,1.329946e-05,0.000752,South America,South America,Non-NATO

In [ ]:
df.head()

,country,active_personnel,aircraft_carriers,armored_fighting_vehicles,attack_aircraft,attack_helicopters,border_coverage_km,coastal_patrol_craft,coastline_coverage_km,corvettes,...,waterway_coverage_km,Power_Score,Power_Rank,Power_Index_Rank_Gap,Total_Assets,Assets_Per_Capita,Budget_to_GDP_Ratio,Continent,Region,Alliance
0,Afghanistan,0,0,5202,0,1,5987,0,0,0,...,1200,9,144.0,143.0,9,2.243183e-07,0.005295,Asia,Asia,Non-NATO
1,Albania,6600,0,1796,0,0,691,19,362,0,...,41,6684,135.0,134.0,84,2.703486e-05,0.011269,Europe,Europe,NATO
2,Algeria,325000,0,26000,42,74,6734,75,998,8,...,0,327203,18.0,17.0,2203,4.684994e-05,0.035717,Africa,Africa,Non-NATO
3,Angola,107000,0,5500,12,15,5369,29,1600,0,...,1300,107638,49.0,48.0,638,1.714959e-05,0.004143,Africa,Africa,Non-NATO
4,Argentina,108000,0,21724,11,0,11968,13,4989,6,...,11000,108625,48.0,47.0,625,1.329946e-05,0.000752,South America,South America,Non-NATO

In [ ]:
save_path = "military_final.csv"
df.to_csv(save_path, index=False)
print(f"DataFrame saved to {save_path}")

DataFrame saved to military_final.csv